//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundsManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountBalanceView
    {
        public int FundId { get; set; }
        public string acct_number { get; set; }
        public string acct_type { get; set; }
        public string acct_name { get; set; }
    }
}
