//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundsManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountsEmployee
    {
        public int Id { get; set; }
        public int FK_AccountsEmployees_Funds { get; set; }
        public int account_id { get; set; }
        public int employee_id { get; set; }
        public decimal amount { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Fund Fund { get; set; }
        public virtual Account Account { get; set; }
    }
}
