//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundsManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankingAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BankingAccount()
        {
            this.AccountsBankingAccounts = new HashSet<AccountsBankingAccount>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public string iban { get; set; }
        public int FK_BankingAccounts_Banks { get; set; }
        public int FK_BankingAccounts_Currencies { get; set; }
        public decimal amount { get; set; }
        public int FK_BankingAccounts_Funds { get; set; }
        public string number { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountsBankingAccount> AccountsBankingAccounts { get; set; }
        public virtual Bank Bank { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Fund Fund { get; set; }
    }
}
