//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundsManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class BondsInvestor
    {
        public int Id { get; set; }
        public int FK_BondsInvestors_Bonds { get; set; }
        public int FK_BondsInvestors_Investors { get; set; }
        public double quantity { get; set; }
    
        public virtual Investor Investor { get; set; }
        public virtual Bond Bond { get; set; }
    }
}
