//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundsManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class BondsTFAMRepaymentDetail
    {
        public int bond_repayment_id { get; set; }
        public int bond_id { get; set; }
        public decimal principal_repaid { get; set; }
        public decimal interest_repaid { get; set; }
        public Nullable<int> movement01_id { get; set; }
        public Nullable<int> movement02_id { get; set; }
    
        public virtual BondsTFAMRepayment BondsTFAMRepayment { get; set; }
        public virtual Movements_Accounts Movements_Accounts { get; set; }
        public virtual Movements_Accounts Movements_Accounts1 { get; set; }
    }
}
