//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundsManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class BondDetail
    {
        public int BondId { get; set; }
        public string Number { get; set; }
        public System.DateTime EmissionDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public decimal PricePerPieces { get; set; }
        public double BondPieces { get; set; }
        public double InterestOnBond { get; set; }
        public double InteretsOnTFFContribution { get; set; }
        public int InvestroId { get; set; }
        public string Investor { get; set; }
        public double InvestorPieces { get; set; }
    }
}
