//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundsManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class BondGeneratedInterestView
    {
        public int Id { get; set; }
        public int bond_id { get; set; }
        public decimal generated_bond_interest { get; set; }
        public decimal generated_tff_interest { get; set; }
        public System.DateTime generated_interest_date { get; set; }
        public Nullable<System.DateTime> payment_interest_date { get; set; }
        public Nullable<int> interest_accounting_movement_id { get; set; }
        public Nullable<int> interest_payment_accounting_movement_id { get; set; }
        public string number { get; set; }
        public int FundId { get; set; }
        public System.DateTime issued { get; set; }
        public decimal amount { get; set; }
        public double interest_on_bond { get; set; }
        public double interest_tff_contribution { get; set; }
        public int active { get; set; }
        public int paid { get; set; }
        public System.DateTime expired { get; set; }
        public int currency_id { get; set; }
        public int can_generate_interest { get; set; }
        public Nullable<int> activation_accounting_movement_id { get; set; }
        public int generated_id { get; set; }
        public System.DateTime GeneratedDate { get; set; }
    }
}
