//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundsManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class BondDetail
    {
        public int BondId { get; set; }
        public string Number { get; set; }
        public System.DateTime EmissionDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public decimal PricePerPieces { get; set; }
        public double BondPieces { get; set; }
        public double InterestOnBond { get; set; }
        public double InteretsOnTFFContribution { get; set; }
        public int InvestroId { get; set; }
        public string Investor { get; set; }
        public double InvestorPieces { get; set; }
    }
}
