//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundsManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bond
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bond()
        {
            this.BondsInvestors = new HashSet<BondsInvestor>();
            this.FundBondInterests = new HashSet<FundBondInterest>();
            this.FundBondProfits = new HashSet<FundBondProfit>();
            this.InvestorBondInterests = new HashSet<InvestorBondInterest>();
        }
    
        public int Id { get; set; }
        public string number { get; set; }
        public System.DateTime issued { get; set; }
        public int FK_Bonds_Funds { get; set; }
        public decimal price { get; set; }
        public double interest_on_bond { get; set; }
        public double interest_tff_contribution { get; set; }
        public double pieces { get; set; }
        public int active { get; set; }
        public Nullable<System.DateTime> expired { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BondsInvestor> BondsInvestors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FundBondInterest> FundBondInterests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FundBondProfit> FundBondProfits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvestorBondInterest> InvestorBondInterests { get; set; }
        public virtual Fund Fund { get; set; }
    }
}
