//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundsManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class BondsTFAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BondsTFAM()
        {
            this.BondsTFAMGeneratedInterests = new HashSet<BondsTFAMGeneratedInterest>();
        }
    
        public int Id { get; set; }
        public string number { get; set; }
        public System.DateTime issued { get; set; }
        public int FK_Bonds_Funds { get; set; }
        public decimal amount { get; set; }
        public double interest_on_bond { get; set; }
        public double interest_tff_contribution { get; set; }
        public int active { get; set; }
        public Nullable<System.DateTime> expired { get; set; }
        public Nullable<int> accounting_movement_id { get; set; }
        public int currency_id { get; set; }
    
        public virtual AccountingMovement AccountingMovement { get; set; }
        public virtual Fund Fund { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BondsTFAMGeneratedInterest> BondsTFAMGeneratedInterests { get; set; }
        public virtual Currency Currency { get; set; }
    }
}
