//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundsManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class BondsTFAMInterestToPay
    {
        public int Id { get; set; }
        public int bond_id { get; set; }
        public decimal generated_bond_interest { get; set; }
        public decimal generated_tff_interest { get; set; }
        public System.DateTime generated_interest_date { get; set; }
        public string number { get; set; }
        public int fund_id { get; set; }
    }
}
