//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundsManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingGeneratedInterestDetail
    {
        public int Id { get; set; }
        public int booking_generated_interest_id { get; set; }
        public int booking_id { get; set; }
        public decimal generated_interest { get; set; }
        public System.DateTime generated_interest_date { get; set; }
        public Nullable<int> accounting_movement_id { get; set; }
    
        public virtual AccountingMovement AccountingMovement { get; set; }
        public virtual BookingGeneratedInterest BookingGeneratedInterest { get; set; }
        public virtual DisbursementBooking DisbursementBooking { get; set; }
    }
}
