//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundsManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingCollectionsDetail
    {
        public int disbursement_collection_id { get; set; }
        public int booking_id { get; set; }
        public decimal amount_collected { get; set; }
        public Nullable<int> movement125_id { get; set; }
        public Nullable<int> movement128_id { get; set; }
        public Nullable<int> movement130_id { get; set; }
    
        public virtual DisbursementCollection DisbursementCollection { get; set; }
        public virtual Movements_Accounts Movements_Accounts { get; set; }
        public virtual Movements_Accounts Movements_Accounts1 { get; set; }
        public virtual Movements_Accounts Movements_Accounts2 { get; set; }
        public virtual DisbursementBooking DisbursementBooking { get; set; }
    }
}
