//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundsManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientContract
    {
        public int fund_id { get; set; }
        public int investment_id { get; set; }
        public string contract { get; set; }
        public int client_id { get; set; }
        public string name { get; set; }
    }
}
