//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundsManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisbursementCollection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DisbursementCollection()
        {
            this.DisbursementCollectionsDetails = new HashSet<DisbursementCollectionsDetail>();
        }
    
        public int id { get; set; }
        public int investment_id { get; set; }
        public System.DateTime collection_date { get; set; }
        public Nullable<int> accounting_movement_id { get; set; }
    
        public virtual Investment Investment { get; set; }
        public virtual AccountingMovement AccountingMovement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DisbursementCollectionsDetail> DisbursementCollectionsDetails { get; set; }
    }
}
