//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundsManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisbursementBooking
    {
        public int id { get; set; }
        public int book_id { get; set; }
        public int disbursement_id { get; set; }
        public decimal amount { get; set; }
        public int currency_id { get; set; }
        public decimal profit_share { get; set; }
        public decimal delay_interest { get; set; }
        public string number { get; set; }
        public System.DateTime starting_date { get; set; }
        public System.DateTime collection_date { get; set; }
        public float exchange_rate { get; set; }
        public int movement125_id { get; set; }
        public int movement128_id { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Disbursement Disbursement { get; set; }
        public virtual Movements_Accounts Movements_Accounts125 { get; set; }
        public virtual Movements_Accounts Movements_Accounts128 { get; set; }
        public virtual DisbursementBook DisbursementBook { get; set; }
    }
}
