//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundsManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisbursementPlusAddendumsView
    {
        public string row_id { get; set; }
        public int Id { get; set; }
        public int currency_id { get; set; }
        public float exchange_rate { get; set; }
        public decimal profit_share { get; set; }
        public decimal amount { get; set; }
        public System.DateTime date { get; set; }
        public string number { get; set; }
        public System.DateTime collection_date { get; set; }
        public bool can_generate_interest { get; set; }
        public Nullable<bool> collected { get; set; }
        public Nullable<int> has_bookings { get; set; }
        public int is_booking { get; set; }
        public Nullable<int> booking_id { get; set; }
        public decimal delay_interest { get; set; }
        public Nullable<int> fund_id { get; set; }
    }
}
