//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundsManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disbursement
    {
        public int Id { get; set; }
        public int investment_id { get; set; }
        public int currency_id { get; set; }
        public int exchange_rate { get; set; }
        public int client_id { get; set; }
        public Nullable<int> underlying_debtor_id { get; set; }
        public Nullable<int> bank_risk_id { get; set; }
        public decimal profit_share { get; set; }
        public decimal amount { get; set; }
        public int fund_id { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual Client Client { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Fund Fund { get; set; }
        public virtual Investment Investment { get; set; }
        public virtual UnderlyingDebtor UnderlyingDebtor { get; set; }
    }
}
