//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundsManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disbursement
    {
        public int Id { get; set; }
        public int investment_id { get; set; }
        public int currency_id { get; set; }
        public float exchange_rate { get; set; }
        public int client_id { get; set; }
        public Nullable<int> underlying_debtor_id { get; set; }
        public Nullable<int> bank_risk_id { get; set; }
        public decimal profit_share { get; set; }
        public decimal amount { get; set; }
        public int fund_id { get; set; }
        public System.DateTime date { get; set; }
        public int sector_id { get; set; }
        public string number { get; set; }
        public System.DateTime collection_date { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual Client Client { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Fund Fund { get; set; }
        public virtual Investment Investment { get; set; }
        public virtual Sector Sector { get; set; }
        public virtual UnderlyingDebtor UnderlyingDebtor { get; set; }
    }
}
