//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundsManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisbursementBooking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DisbursementBooking()
        {
            this.BookingCollectionsDetails = new HashSet<BookingCollectionsDetail>();
            this.BookingGeneratedInterestDetails = new HashSet<BookingGeneratedInterestDetail>();
        }
    
        public int id { get; set; }
        public int book_id { get; set; }
        public int disbursement_id { get; set; }
        public decimal amount { get; set; }
        public int currency_id { get; set; }
        public decimal profit_share { get; set; }
        public decimal delay_interest { get; set; }
        public string number { get; set; }
        public System.DateTime starting_date { get; set; }
        public System.DateTime collection_date { get; set; }
        public float exchange_rate { get; set; }
        public int movement125_id { get; set; }
        public int movement128_id { get; set; }
        public bool collected { get; set; }
        public bool can_generate_interest { get; set; }
        public bool has_booking { get; set; }
        public Nullable<int> parent_book_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingCollectionsDetail> BookingCollectionsDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingGeneratedInterestDetail> BookingGeneratedInterestDetails { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual DisbursementBook DisbursementBook { get; set; }
        public virtual Disbursement Disbursement { get; set; }
        public virtual Movements_Accounts Movements_Accounts { get; set; }
        public virtual Movements_Accounts Movements_Accounts1 { get; set; }
    }
}
