//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundsManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisbursementCollection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DisbursementCollection()
        {
            this.BookingCollectionsDetails = new HashSet<BookingCollectionsDetail>();
            this.DisbursementCollectionsDetails = new HashSet<DisbursementCollectionsDetail>();
        }
    
        public int id { get; set; }
        public int investment_id { get; set; }
        public System.DateTime collection_date { get; set; }
        public Nullable<int> accounting_movement_id { get; set; }
    
        public virtual AccountingMovement AccountingMovement { get; set; }
        public virtual Investment Investment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingCollectionsDetail> BookingCollectionsDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DisbursementCollectionsDetail> DisbursementCollectionsDetails { get; set; }
    }
}
