//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundsManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisbursementOverdueDetail
    {
        public int Id { get; set; }
        public int disbursement_overdue_id { get; set; }
        public int disbursement_id { get; set; }
        public decimal generated_overdue { get; set; }
        public decimal monthly_rate { get; set; }
        public System.DateTime overdue_date_from { get; set; }
        public System.DateTime overdue_date_to { get; set; }
        public Nullable<int> overdue_accounting_movement_id { get; set; }
    
        public virtual AccountingMovement AccountingMovement { get; set; }
        public virtual DisbursementOverdue DisbursementOverdue { get; set; }
        public virtual Disbursement Disbursement { get; set; }
    }
}
