//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundsManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disbursement_dates
    {
        public int Id { get; set; }
        public System.DateTime date { get; set; }
        public int day { get; set; }
        public int disbursement_id { get; set; }
        public int fund_id { get; set; }
    
        public virtual Fund Fund { get; set; }
    }
}
