//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundsManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class FundBondInterest
    {
        public int Id { get; set; }
        public int BondId { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime InterestDate { get; set; }
        public bool Extracted { get; set; }
        public Nullable<System.DateTime> ExtractionDate { get; set; }
    
        public virtual Bond Bond { get; set; }
    }
}
