//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundsManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class FundBondInterest
    {
        public int Id { get; set; }
        public int BondId { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime InterestDate { get; set; }
        public bool Extracted { get; set; }
        public Nullable<System.DateTime> ExtractionDate { get; set; }
    }
}
