//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundsManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvestmentsView
    {
        public int fund_id { get; set; }
        public int investment_id { get; set; }
        public string contract { get; set; }
        public System.DateTime investment_date { get; set; }
        public Nullable<decimal> total_disbursement { get; set; }
        public Nullable<decimal> investment_profit_share { get; set; }
        public Nullable<int> payment_id { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
        public int disbursement_id { get; set; }
        public string disbursement_number { get; set; }
        public Nullable<System.DateTime> disbursement_pay_date { get; set; }
        public decimal amount { get; set; }
        public float exchange_rate { get; set; }
        public decimal profit_share { get; set; }
        public System.DateTime disbursement_date { get; set; }
        public System.DateTime collection_date { get; set; }
        public Nullable<int> bank_risk_id { get; set; }
        public string bank_name { get; set; }
        public int client_id { get; set; }
        public string client { get; set; }
        public int sector_id { get; set; }
        public string sector { get; set; }
    }
}
