//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundsManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Loan()
        {
            this.Loan_Repayments = new HashSet<Loan_Repayments>();
            this.LoanGeneratedInterestDetails = new HashSet<LoanGeneratedInterestDetail>();
        }
    
        public int Id { get; set; }
        public int lender_id { get; set; }
        public decimal interest { get; set; }
        public decimal amount { get; set; }
        public string reference { get; set; }
        public System.DateTime start { get; set; }
        public System.DateTime end { get; set; }
        public int fund_id { get; set; }
        public int currency_id { get; set; }
        public int accounting_movement_id { get; set; }
        public Nullable<bool> renegotiated { get; set; }
        public Nullable<int> loan_origin_id { get; set; }
        public int interest_base { get; set; }
    
        public virtual AccountingMovement AccountingMovement { get; set; }
        public virtual Creditor Creditor { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Fund Fund { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Loan_Repayments> Loan_Repayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanGeneratedInterestDetail> LoanGeneratedInterestDetails { get; set; }
    }
}
