//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundsManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loans_View
    {
        public int Id { get; set; }
        public int fund_id { get; set; }
        public int lender_id { get; set; }
        public string name { get; set; }
        public decimal interest { get; set; }
        public decimal amount { get; set; }
        public string reference { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public Nullable<decimal> generated_interest { get; set; }
        public int currency_id { get; set; }
        public string currency_name { get; set; }
        public Nullable<bool> renegotiated { get; set; }
        public Nullable<int> loan_origin_id { get; set; }
    }
}
