//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundsManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoansRepaymentsView
    {
        public int Id { get; set; }
        public int lender_id { get; set; }
        public string reference { get; set; }
        public System.DateTime start { get; set; }
        public System.DateTime end { get; set; }
        public int fund_id { get; set; }
        public int currency_id { get; set; }
        public int accounting_movement_id { get; set; }
        public Nullable<bool> renegotiated { get; set; }
        public Nullable<int> loan_origin_id { get; set; }
        public int interest_base { get; set; }
        public decimal amount { get; set; }
        public Nullable<decimal> amount_repaid { get; set; }
        public decimal interest { get; set; }
        public Nullable<decimal> interest_accrued { get; set; }
        public Nullable<decimal> interest_repaid { get; set; }
    }
}
