//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundsManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movements_Accounts
    {
        public int Id { get; set; }
        public Nullable<int> FK_Movements_Accounts_Subaccounts { get; set; }
        public int FK_Movements_Accounts_AccountingMovements { get; set; }
        public decimal credit { get; set; }
        public decimal debit { get; set; }
        public Nullable<int> subaccount { get; set; }
        public Nullable<int> subaccount_type { get; set; }
        public int FK_Movements_Accounts_Funds { get; set; }
        public Nullable<int> FK_Movements_Accounts_Accounts { get; set; }
        public decimal acc_amount { get; set; }
        public decimal subacc_amount { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Fund Fund { get; set; }
        public virtual Subaccount Subaccount1 { get; set; }
        public virtual AccountingMovement AccountingMovement { get; set; }
    }
}
