//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundsManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtherDetailsView
    {
        public string source { get; set; }
        public string Row_Id { get; set; }
        public int Id { get; set; }
        public int DetailType { get; set; }
        public string name { get; set; }
        public int fund_id { get; set; }
    }
}
