//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundsManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtherDetail
    {
        public int Id { get; set; }
        public string name { get; set; }
        public int FK_OtherDetails_Funds { get; set; }
        public Nullable<int> FK_OtherDetails_Accounts { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Fund Fund { get; set; }
    }
}
