//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundsManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtherDetail
    {
        public int Id { get; set; }
        public string name { get; set; }
        public int FK_OtherDetails_Funds { get; set; }
        public int subacct_id { get; set; }
        public string number { get; set; }
    
        public virtual Subaccount Subaccount { get; set; }
        public virtual Fund Fund { get; set; }
    }
}
