//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundsManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfitResult
    {
        public int Id { get; set; }
        public string Reference { get; set; }
        public string description { get; set; }
        public int TypeId { get; set; }
        public string AccountType { get; set; }
        public string Account { get; set; }
        public string SubAccount { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Debit { get; set; }
        public decimal Credit { get; set; }
        public Nullable<decimal> Shift_Amount { get; set; }
        public decimal Acc_Amount { get; set; }
        public decimal SubAcc_amount { get; set; }
    }
}
