//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundsManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Template_Profit_Loss
    {
        public string AccountType { get; set; }
        public int account_id { get; set; }
        public string Account { get; set; }
        public string SubAccount { get; set; }
        public Nullable<decimal> Shift_Amount { get; set; }
        public Nullable<decimal> Shift_Amount_Last_Period { get; set; }
        public Nullable<decimal> ProfitLoss { get; set; }
        public Nullable<decimal> ProfitLossLastPeriod { get; set; }
    }
}
