//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundsManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class tempOverdue
    {
        public int Id { get; set; }
        public Nullable<int> disbursement_id { get; set; }
        public string reference { get; set; }
        public string number { get; set; }
        public Nullable<System.DateTime> collection_date { get; set; }
        public Nullable<decimal> to_be_collected { get; set; }
        public Nullable<decimal> principal_tbc { get; set; }
        public Nullable<decimal> profit_tbc { get; set; }
        public Nullable<decimal> delay_tbc { get; set; }
        public Nullable<System.DateTime> from_date { get; set; }
        public Nullable<System.DateTime> to_date { get; set; }
        public Nullable<decimal> monthly_rate { get; set; }
        public Nullable<decimal> overdue { get; set; }
        public Nullable<int> days { get; set; }
        public Nullable<float> exchange_rate { get; set; }
    }
}
