//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundsManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnlinkedDisbursement
    {
        public int fund_id { get; set; }
        public int investment_id { get; set; }
        public string contract { get; set; }
        public System.DateTime investment_date { get; set; }
        public Nullable<decimal> total_disbursement { get; set; }
        public Nullable<decimal> investment_profit_share { get; set; }
        public Nullable<int> payment_id { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
        public int disbursement_id { get; set; }
        public string disbursement_number { get; set; }
        public Nullable<System.DateTime> disbursement_pay_date { get; set; }
        public int currency_id { get; set; }
        public decimal amount { get; set; }
        public float exchange_rate { get; set; }
        public decimal profit_share { get; set; }
        public System.DateTime disbursement_date { get; set; }
        public string collection_date { get; set; }
        public bool can_generate_interest { get; set; }
        public Nullable<bool> collected { get; set; }
        public Nullable<int> bank_risk_id { get; set; }
        public string bank_name { get; set; }
        public int client_id { get; set; }
        public string client { get; set; }
        public int sector_id { get; set; }
        public string sector { get; set; }
        public Nullable<decimal> generated_interest { get; set; }
        public Nullable<decimal> total_to_be_collected { get; set; }
        public Nullable<decimal> collected_amount { get; set; }
        public Nullable<bool> has_bookings { get; set; }
    }
}
